# तिथियों के नाम (1 से 30)
TITHIS = {
  1: "Pratipada (प्रतिपदा)",
  2: "Dwitiya (द्वितीया)",
  3: "Tritiya (तृतीया)",
  4: "Chaturthi (चतुर्थी)",
  5: "Panchami (पंचमी)",
  6: "Shashthi (षष्ठी)",
  7: "Saptami (सप्तमी)",
  8: "Ashtami (अष्टमी)",
  9: "Navami (नवमी)",
  10: "Dashami (दशमी)",
  11: "Ekadashi (एकादशी)",
  12: "Dwadashi (द्वादशी)",
  13: "Trayodashi (त्रयोदशी)",
  14: "Chaturdashi (चतुर्दशी)",
  15: "Purnima (पूर्णिमा)",
  16: "Pratipada (प्रतिपदा)",
  17: "Dwitiya (द्वितीया)",
  18: "Tritiya (तृतीया)",
  19: "Chaturthi (चतुर्थी)",
  20: "Panchami (पंचमी)",
  21: "Shashthi (षष्ठी)",
  22: "Saptami (सप्तमी)",
  23: "Ashtami (अष्टमी)",
  24: "Navami (नवमी)",
  25: "Dashami (दशमी)",
  26: "Ekadashi (एकादशी)",
  27: "Dwadashi (द्वादशी)",
  28: "Trayodashi (त्रयोदशी)",
  29: "Chaturdashi (चतुर्दशी)",
  30: "Amavasya (अमावस्या)",
}

# नक्षत्रों के नाम (1 से 27)
NAKSHATRAS = {
  1: "Ashwini",
  2: "Bharani",
  3: "Krittika",
  4: "Rohini",
  5: "Mrigashira",
  6: "Ardra",
  7: "Punarvasu",
  8: "Pushya",
  9: "Ashlesha",
  10: "Magha",
  11: "Purva Phalguni",
  12: "Uttara Phalguni",
  13: "Hasta",
  14: "Chitra",
  15: "Swati",
  16: "Vishakha",
  17: "Anuradha",
  18: "Jyeshtha",
  19: "Mula",
  20: "Purva Ashadha",
  21: "Uttara Ashadha",
  22: "Shravana",
  23: "Dhanishta",
  24: "Shatabhisha",
  25: "Purva Bhadrapada",
  26: "Uttara Bhadrapada",
  27: "Revati",
}

# योगों के नाम (1 से 27)
YOGAS = {
  1: "Vishkumbha",
  2: "Priti",
  3: "Ayushman",
  4: "Saubhagya",
  5: "Shobhana",
  6: "Atiganda",
  7: "Sukarma",
  8: "Dhriti",
  9: "Shula",
  10: "Ganda",
  11: "Vriddhi",
  12: "Dhruva",
  13: "Vyaghata",
  14: "Harshana",
  15: "Vajra",
  16: "Siddhi",
  17: "Vyatipata",
  18: "Variyan",
  19: "Parigha",
  20: "Shiva",
  21: "Siddha",
  22: "Sadhya",
  23: "Shubha",
  24: "Shukla",
  25: "Brahma",
  26: "Indra",
  27: "Vaidhriti",
}

# करणों के नाम
KARANAS = {
  1: "Bava",
  2: "Balava",
  3: "Kaulava",
  4: "Taitila",
  5: "Gara",
  6: "Vanija",
  7: "Vishti",
  8: "Bavani",
  9: "Balava",
  10: "Kaulava",
  11: "Shakuni",
}